---
- name: Install rbenv dependencies
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - gcc
    - openssl-devel
    - readline-devel
    - zlib-devel

- name: Check rbenv install
  stat:
    path: "{{ rbenv_path }}"
  register: rbenv_exists

- name: Download rbenv_ruby-build
  become_user: ec2-user
  uri:
    url: https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer
    return_content: yes
  register: rbenv_installer
  when: not rbenv_exists.stat.exists

- name: Run rbenv_ruby-build
  become_user: ec2-user
  shell: "{{ rbenv_installer.content }}"
  args:
    chdir: /home/ec2-user/
  when: not rbenv_exists.stat.exists

- name: Add rbenv to PATH
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'

- name: eval rbenv init
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'

- name: Load rbenv setting
  become_user: ec2-user
  shell: bash -lc "source ~/.bash_profile"

- name: Check ruby installed
  stat: 
    path: "{{ rbenv_path }}/shims/ruby"
  register: rbenv_check_install

- name: Install Ruby
  become_user: ec2-user
  shell: bash -lc "rbenv install {{ ruby_version }}"
  when: not rbenv_check_install.stat.exists

- name: Set default Ruby version g
  become_user: ec2-user
  shell: bash -lc "rbenv global {{ ruby_version }}"

- name: Set default Ruby version h
  become_user: ec2-user
  shell: bash -lc "rbenv rehash"

- name: Load ruby setting
  become_user: ec2-user
  shell: bash -lc "source ~/.bash_profile"

