---
- name: Install rbenv dependencies
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - gcc
    - openssl-devel
    - readline-devel
    - zlib-devel

- name: rbenvがインストール済か確認
  shell: "{{ rbenv_path }}/bin/rbenv --version"
  register: rbenv_exists
  changed_when: False
  ignore_errors: yes

- name: rbenvが未インストールならrbenvをインストール
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: "{{ rbenv_path }}"
  when: rbenv_exists is failed

- name: ruby-buildをインストール
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: "{{ rbenv_path }}/plugins/ruby-build"
  when: rbenv_exists is failed

- name: rbenv installを実行できるようにする
  # ec2-userで実行
  become_user: ec2-user
  command: "{{ rbenv_path }}/plugins/ruby-build/install.sh"
  when:  rbenv_exists is failed

- name: 環境変数PATHにrbenvのパスを設定
  blockinfile:
    dest: "{{ home_path }}/.bash_profile"
    create: yes
    insertafter: '^PATH=\$PATH:\$HOME/bin$'
    content: |
      export RBENV_ROOT={{ rbenv_path }}
      export PATH="$RBENV_ROOT/bin:$PATH"
      eval "$(rbenv init -)"
  when: rbenv_exists is failed


# - name: Install rbenv and dependencies
#   ansible.builtin.shell: curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
#   args:
#     executable: /bin/bash

# - name: Add rbenv to PATH and initialize it
#   ansible.builtin.lineinfile:
#     path: /home/ec2-user/.bash_profile
#     line: '{{ item }}'
#   with_items:
#     - 'export PATH="$HOME/.rbenv/bin:$PATH"'
#     - 'eval "$(rbenv init -)"'

# - name: Reload .bash_profile
#   ansible.builtin.shell: source /home/ec2-user/.bash_profile
#   args:
#     executable: /bin/bash

# - name: Check rbenv version
#   ansible.builtin.command: rbenv --version

- name: Install Ruby 3.1.2
  ansible.builtin.command: rbenv install 3.1.2
  args:
    creates: /home/ec2-user/.rbenv/versions/3.1.2

- name: Set Ruby 3.1.2 as the global version
  ansible.builtin.command: rbenv global 3.1.2

- name: Run rbenv rehash
  ansible.builtin.command: rbenv rehash

- name: Check Ruby version
  ansible.builtin.command: ruby --version
