version: 2.1

orbs:
  ansible: orbss/ansible-playbook@0.0.5
  aws-cli: circleci/aws-cli@3.1.5
  ruby: circleci/ruby@1.2.0


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  deploy-cloudformation-stacks:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: Deploy All CloudFormation Stacks
          command: |
            aws cloudformation deploy --template-file cloudformation/VPC.yml --stack-name VPC-subnet-01 
            aws cloudformation deploy --template-file cloudformation/SecurityGroup.yml --stack-name Security-01 
            aws cloudformation deploy --template-file cloudformation/EC2.yml --stack-name EC2-01
            aws cloudformation deploy --template-file cloudformation/ALB.yml --stack-name ALB-01
            aws cloudformation deploy --template-file cloudformation/RDS.yml --stack-name RDS-01
  
  run-ansible-playbook:
    executor: ansible/default
    steps:
      - checkout
      - run:
          name: Install Ansible
          command: |
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo apt-add-repository --yes --update ppa:ansible/ansible
            sudo apt-get install -y ansible
          # Ansible SSH接続時のホスト鍵自動登録を有効化
      - run:
          name: Enable Host Key Checking
          command: |
            mkdir -p ~/.ssh
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - add_ssh_keys:
          fingerprints:
          - d7:9f:96:ee:bf:70:d3:ea:da:27:f5:56:0b:82:a3:79:56:2c:ab:49
      # - ansible/install
      # - run:
      #     name: Set up SSH key
      #     command: |
      #       echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      #       chmod 600 ~/.ssh/id_rsa
      # - run:
      #     name: Run Ansible playbook
      #     command: ansible-playbook -i ansible/inventory ansible/playbook.yml
      - ansible/install
      - run:
          name: Run Ansible playbook
          command: ansible-playbook -i ansible/inventory ansible/playbook.yml \-u ec2-user \--private-key ~/.ssh/raisetech4thv2

          
  run-serverspec:
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Install Serverspec and run tests
          command: |
            gem install serverspec
            rake --rakefile=serverspec/Rakefile spec

workflows:
  version: 2
  deploy_and_test:
    jobs:
      - deploy-cloudformation-stacks
      - run-ansible-playbook:
          requires:
            - deploy-cloudformation-stacks
      - run-serverspec:
          requires:
            - run-ansible-playbook
